/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y6uAjdOIYnb
 */
import Link from "next/link"

export function InformationFooter() {
  return (
    <footer className="bg-transparent border-t-2 border-t-slate-800 text-white p-8">
      <div className="container mx-auto flex flex-col md:flex-row justify-between items-center">
        <div className="mb-6 md:mb-0">
          {/* <div className="flex flex-col items-center mb-2">
            <img
              alt="Revise Logo"
              className="h-50 w-50 mr-2"
              height="140"
              src="/logoR-circle.png"
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width="40"
            />
          </div> */}
          <p className="text-sm">© Rewise 2023</p>
        </div>
        <div className="mb-6 md:mb-0">
          <h5 className="text-lg font-semibold mb-2">More Info</h5>
          <ul>
            <li className="mb-1">
              <Link className="hover:underline" href="#">
                About
              </Link>
            </li>
            <li className="mb-1">
              <Link className="hover:underline" href="#">
                FAQs
              </Link>
            </li>
            <li className="mb-1">
              <Link className="hover:underline" href="#">
                Contact Us
              </Link>
            </li>
            <li className="mb-1">
              <Link className="hover:underline" href="#">
                Policies
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h5 className="text-lg font-semibold mb-2">Follow Us</h5>
          <ul>
            <li className="mb-1 flex items-center">
              <FacebookIcon className="h-4 w-4 mr-2" />
              <Link className="hover:underline" href="#">
                Facebook
              </Link>
            </li>
            <li className="flex items-center">
              <InstagramIcon className="h-4 w-4 mr-2" />
              <Link className="hover:underline" href="#">
                Instagram
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  )
}


function FacebookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
