/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rRBlufM
 */
import { Button } from "@/components/ui/button";
import { proFeaturesMonthly, proFeaturesYearly, freeFeatures } from "@/constants";
import { cn } from "@/lib/utils";
import { Badge } from "./ui/badge";
import { Check } from "lucide-react";

export function PricingComponent() {
  return (
    <div className="flex md:flex-row flex-col gap-x-8 px-8 items-center justify-center">
      <div className="p-6 -white shadow-lg rounded-lg dark:bg-zinc-850 justify-between border border-gray-300">
        <div className="h-full">
          <h3 className="text-2xl font-bold text-center">Free</h3>
          <ul className="">
            {freeFeatures.map((tool) => (
              <li key={tool.href} className="p-3 border-black/5 flex items-center justify-between">
                <div className="flex items-center gap-x-3">
                  <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                    <tool.icon className={cn("w-6 h-6", tool.color)} />
                  </div>
                  <div className="font-semibold text-sm">
                    {tool.label}
                  </div>
                </div>
                {tool.badge && (<div>
                  <Badge variant="outline" className="uppercase text-xs py-1">
                    {tool.badge}
                  </Badge>
                </div>)}
              </li>
            ))}
          </ul>
        </div>
        <div className="text-center mt-6">
          Current plan
        </div>
      </div>
      <div className="p-6 -white shadow-lg rounded-lg dark:bg-zinc-850 justify-between border border-gray-300">
        <div>
          <h3 className="text-2xl font-bold text-center">Monthly</h3>
          <div className="mt-4 text-center text-zinc-600 dark:text-zinc-400">
            <span className="text-4xl font-bold">€10</span>/ month
          </div>
          <ul className="">
            {proFeaturesMonthly.map((tool) => (
              <li key={tool.href} className="p-3 border-black/5 flex items-center justify-between">
                <div className="flex items-center gap-x-3">
                  <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                    <tool.icon className={cn("w-6 h-6", tool.color)} />
                  </div>
                  <div className="font-semibold text-sm">
                    {tool.label}
                  </div>
                </div>
                {tool.badge && (<div>
                  <Badge variant="outline" className="uppercase text-xs py-1">
                    {tool.badge}
                  </Badge>
                </div>)}
              </li>
            ))}
          </ul>
        </div>
        <div className="mt-6">
          <Button className="w-full">Get Started</Button>
        </div>
      </div>
      <div className="p-6 shadow-lg rounded-lg dark:bg-zinc-850 border border-gray-300">
        <div className="flex flex-col">
        <div className="px-3 py-1 text-sm text-white items-center justify-center bg-gradient-to-r from-pink-500 to-purple-500 rounded-full text-center">
          Popular
        </div>
          <h3 className="text-2xl font-bold text-center">
            Full access 
          </h3>
          <div className="mt-4 text-center text-zinc-600 dark:text-zinc-400">
            <span className="text-4xl font-bold">€35</span>
            <h5></h5>
          </div>
          <ul className="">
            {proFeaturesYearly.map((tool) => (
              <li key={tool.href} className="p-3 border-black/5 flex items-center justify-between">
                <div className="flex items-center gap-x-3">
                  <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                    <tool.icon className={cn("w-6 h-6", tool.color)} />
                  </div>
                  <div className="font-semibold text-sm">
                    {tool.label}
                  </div>
                </div>
                {tool.badge && (<div>
                  <Badge variant="outline" className="uppercase text-xs py-1">
                    {tool.badge}
                  </Badge>
                </div>)}
              </li>
            ))}
          </ul>
        </div>
        <div className="mt-6">
          <Button className="w-full bg-gradient-to-r from-pink-500 to-purple-500">
            Get Started
          </Button>
        </div>
      </div>
    </div>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
