"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rRBlufM
 */

import { Button } from "@/components/ui/button";
import {
  proFeaturesMonthly,
  proFeaturesYearly,
  freeFeatures,
} from "@/constants";
import { cn } from "@/lib/utils";
import { Badge } from "./ui/badge";
import { useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { ScrollArea } from "./ui/scroll-area";

export function PricingComponent() {
  const onSubscribeMonthly = async () => {
    try {
      setLoading(true);
      const response = await axios.get("/api/stripe-monthly");

      console.log("response url", response.data.url);
      window.location.href = response.data.url;
    } catch (error) {
      toast.error("Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const onPaymentYearly = async () => {
    try {
      setLoading(true);
      const response = await axios.get("/api/stripe-yearly");

      window.location.href = response.data.url;
    } catch (error) {
      toast.error("Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const [loading, setLoading] = useState(false);
  return (
    <div className="mb-9">
    <div className="md:block hidden min-h-screen">
      <div className="flex md:flex-row flex-col gap-x-8 px-8 items-center justify-center md:space-y-0 space-y-4">
        <div className="p-6 w-auto shadow-lg rounded-lg dark:bg-zinc-850 justify-between border border-gray-300">
          <div className="h-full">
            <h3 className="text-2xl font-bold text-center">Free</h3>
            <ul className="">
              {freeFeatures.map((tool) => (
                <li
                  key={tool.href}
                  className="p-3 border-black/5 flex items-center justify-between"
                >
                  <div className="flex items-center gap-x-3">
                    <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                      <tool.icon className={cn("w-6 h-6", tool.color)} />
                    </div>
                    <div className="font-semibold text-sm">{tool.label}</div>
                  </div>
                  {tool.badge && (
                    <div>
                      <Badge
                        variant="outline"
                        className="uppercase text-xs py-1"
                      >
                        {tool.badge}
                      </Badge>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
          <div className="text-center mt-6">Current plan</div>
        </div>
        <div className="p-6 w-auto shadow-lg rounded-lg dark:bg-zinc-850 justify-between border border-gray-300">
          <div>
            <h3 className="text-2xl font-bold text-center">Monthly</h3>
            <div className="mt-4 text-center text-zinc-600 dark:text-zinc-400">
              <span className="text-4xl font-bold">€11.99</span>/ month
            </div>
            <ul className="">
              {proFeaturesMonthly.map((tool) => (
                <li
                  key={tool.href}
                  className="p-3 border-black/5 flex items-center justify-between"
                >
                  <div className="flex items-center gap-x-3">
                    <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                      <tool.icon className={cn("w-6 h-6", tool.color)} />
                    </div>
                    <div className="font-semibold text-sm">{tool.label}</div>
                  </div>
                  {tool.badge && (
                    <div>
                      <Badge
                        variant="outline"
                        className="uppercase text-xs py-1"
                      >
                        {tool.badge}
                      </Badge>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6">
            <Button
              className="w-full"
              onClick={onSubscribeMonthly}
              disabled={loading}
            >
              Get Started
            </Button>
          </div>
        </div>
        <div className="p-6 w-auto shadow-lg rounded-lg dark:bg-zinc-850 border border-gray-300">
          <div className="flex flex-col">
            <div className="px-3 my-2 text-sm text-white items-center justify-center bg-gradient-to-r via-pink-500 to-purple-500 from-blue-500 rounded-full text-center">
              Best Value
            </div>
            <h3 className="text-2xl font-bold text-center">Full access</h3>
            <div className="mt-4 text-center text-zinc-600 dark:text-zinc-400">
              <span className="text-4xl font-bold">€39.99</span>
            </div>
            <ul className="">
              {proFeaturesYearly.map((tool) => (
                <li
                  key={tool.href}
                  className="p-3 border-black/5 flex items-center justify-between"
                >
                  <div className="flex items-center gap-x-3">
                    <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                      <tool.icon className={cn("w-6 h-6", tool.color)} />
                    </div>
                    <div className="font-semibold text-sm">{tool.label}</div>
                  </div>
                  {tool.badge && (
                    <div>
                      <Badge
                        variant="outline"
                        className="uppercase text-xs py-1"
                      >
                        {tool.badge}
                      </Badge>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6">
            <Button
              className="w-full bg-gradient-to-r from-pink-500 to-purple-500"
              onClick={onPaymentYearly}
              disabled={loading}
            >
              Get Started
            </Button>
          </div>
        </div>
      </div>
    </div>
    <div className="md:hidden min-h-screen max-h-screen">
      <div className="flex md:flex-row flex-col gap-x-8 px-8 items-center justify-center md:space-y-0 space-y-4">
        <div className="p-6 w-auto shadow-lg rounded-lg dark:bg-zinc-850 justify-between border border-gray-300">
          <div className="h-full">
            <h3 className="text-2xl font-bold text-center">Free</h3>
            <ul className="">
              {freeFeatures.map((tool) => (
                <li
                  key={tool.href}
                  className="p-3 border-black/5 flex items-center justify-between"
                >
                  <div className="flex items-center gap-x-3">
                    <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                      <tool.icon className={cn("w-6 h-6", tool.color)} />
                    </div>
                    <div className="font-semibold text-sm">{tool.label}</div>
                  </div>
                  {tool.badge && (
                    <div>
                      <Badge
                        variant="outline"
                        className="uppercase text-xs py-1"
                      >
                        {tool.badge}
                      </Badge>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
          <div className="text-center mt-6">Current plan</div>
        </div>
        <div className="p-6 w-auto shadow-lg rounded-lg dark:bg-zinc-850 justify-between border border-gray-300">
          <div>
            <h3 className="text-2xl font-bold text-center">Monthly</h3>
            <div className="mt-4 text-center text-zinc-600 dark:text-zinc-400">
              <span className="text-4xl font-bold">€11.99</span>/ month
            </div>
            <ul className="">
              {proFeaturesMonthly.map((tool) => (
                <li
                  key={tool.href}
                  className="p-3 border-black/5 flex items-center justify-between"
                >
                  <div className="flex items-center gap-x-3">
                    <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                      <tool.icon className={cn("w-6 h-6", tool.color)} />
                    </div>
                    <div className="font-semibold text-sm">{tool.label}</div>
                  </div>
                  {tool.badge && (
                    <div>
                      <Badge
                        variant="outline"
                        className="uppercase text-xs py-1"
                      >
                        {tool.badge}
                      </Badge>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6">
            <Button
              className="w-full"
              onClick={onSubscribeMonthly}
              disabled={loading}
            >
              Get Started
            </Button>
          </div>
        </div>
        <div className="p-6 w-auto shadow-lg rounded-lg dark:bg-zinc-850 border border-gray-300">
          <div className="flex flex-col">
            <div className="px-3 my-2 text-sm text-white items-center justify-center bg-gradient-to-r via-pink-500 to-purple-500 from-blue-500 rounded-full text-center">
              Best Value
            </div>
            <h3 className="text-2xl font-bold text-center">Full access</h3>
            <div className="mt-4 text-center text-zinc-600 dark:text-zinc-400">
              <span className="text-4xl font-bold">€39.99</span>
            </div>
            <ul className="">
              {proFeaturesYearly.map((tool) => (
                <li
                  key={tool.href}
                  className="p-3 border-black/5 flex items-center justify-between"
                >
                  <div className="flex items-center gap-x-3">
                    <div className={cn("p-2 w-fit rounded-md", tool.bgColor)}>
                      <tool.icon className={cn("w-6 h-6", tool.color)} />
                    </div>
                    <div className="font-semibold text-sm">{tool.label}</div>
                  </div>
                  {tool.badge && (
                    <div>
                      <Badge
                        variant="outline"
                        className="uppercase text-xs py-1"
                      >
                        {tool.badge}
                      </Badge>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6">
            <Button
              className="w-full bg-gradient-to-r from-blue-500 to-purple-500"
              onClick={onPaymentYearly}
              disabled={loading}
            >
              Get Started
            </Button>
          </div>
        </div>
      </div>
    </div>
    </div>
  );
}

